package org.dmace.demo.web.servlet;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

public class PrimitiveServlet extends HttpServlet {

    public void doGet(HttpServletRequest request, HttpServletResponse response ) throws IOException {

        String message = getServletConfig().getInitParameter("message");

        response.setContentType("text/html");
        response.setCharacterEncoding( "UTF-8" );
        PrintWriter out = null;

        try {
            out = response.getWriter();
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<meta charset=\"utf-8\" />");
            out.println("<title>Test</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<p>This page was generated by a servlet.</p>");
            out.println("<p>The message is: <strong>");
            out.println(message);
            out.println("</strong></p>");
            out.println("</body>");
            out.println("</html>");
        } finally {
            if(out!=null) {
                out.flush();
                out.close();
            }
        }
    }

}
